name: Update Raspberry Pi and run docker

on:
  # listen to manual trigger
  workflow_dispatch:

  # listen to push
  push:
    branches: [main]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Nested ssh to VM and then to RPI with docker commands
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} /bin/bash <<- 'SSH_VM'
            ls -la
            ssh -p 2222 pi@localhost /bin/bash <<- 'SSH_RPI'
              cd /home/pi/frontend
              git pull
              ls -la
              docker-compose build
              docker-compose up --detach
          SSH_RPI
          SSH_VM
